// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using contacts.Data;

namespace contacts.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("contacts.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.HasKey("Id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("contacts.Models.Contact", b =>
                {
                    b.OwnsOne("contacts.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("ContactId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .HasColumnName("email_address")
                                .HasColumnType("text");

                            b1.HasKey("ContactId");

                            b1.ToTable("contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsOne("contacts.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<int>("ContactId")
                                .HasColumnType("integer");

                            b1.Property<string>("FirstName")
                                .HasColumnName("first_name")
                                .HasColumnType("text");

                            b1.Property<string>("LastName")
                                .HasColumnName("last_name")
                                .HasColumnType("text");

                            b1.HasKey("ContactId");

                            b1.ToTable("contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });

                    b.OwnsMany("contacts.ValueObjects.PhoneNumber", "PhoneNumbers", b1 =>
                        {
                            b1.Property<int>("ContactId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Number")
                                .HasColumnType("text");

                            b1.HasKey("ContactId", "Id");

                            b1.ToTable("PhoneNumber");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
